### ISSUE TITLE
Update to OpenSearch Dashboards 2.0.0

### ISSUE THREAD

**Issue by kavilla** [lguillaud/osd_transform_vis#1]
OpenSearch Dashboards 2.0.0 did a series of dependency updates that required changes from certain plugins to be able to build and run properly.

Please check out this issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1206

Please let me know if you would like any assistance with this.

Thank you!

**Comment by lguillaud** [comment]
Hello @kavilla 
Thanks, will have a look and keep you updated.

**Comment by lguillaud** [comment]
Hello,

1. Installed dev env for Opensearh-Dashboards 2.0.0-rc1 
2. Made appropriate changes in dependencies versions
3. Released candidate version: https://github.com/lguillaud/osd_transform_vis/releases/tag/untagged-99f7262c4f8f32c22bde
