### ISSUE TITLE
Created visualizasion does not save when Javascript is present

### ISSUE THREAD

**Issue by LuisFFadista** [lguillaud/osd_transform_vis#10]
Hello,

I have an Opensearch + Opensearch Dashboards v2.11.0 docker environment, with the only changes being the ones to support the 'osd_transform_vis' plugin.

When attempting to create a visualization without JS the plugin is saved successfully. However when any JS is present a 504 Gateway Time-out error is shown. Here is the error presented, and the stack-trace:

![imagem](https://github.com/lguillaud/osd_transform_vis/assets/167180369/569f8f09-edf3-4fd0-856e-6384f7b0995b)

![imagem](https://github.com/lguillaud/osd_transform_vis/assets/167180369/4c6d1941-e53e-42a4-8119-2f88dbca2fde)

I am using 'sample_tabulator' in order to replicate these errors.

Other than this, everything else works normally (DSL Querying, rendering, etc.).

If any adicional information is required to identify/replicate the issue, let me know.
Thank you for your time.

**Comment by lguillaud** [comment]
Hello,
I have never encountered such an issue.
Did you update the opensearch_dashboards.yml file according to the README file ? (prerequisites section)
Could you please check your config files are fine in your docker container ?
thanks.

**Comment by LuisFFadista** [comment]
Just checked, all changes in the prerequisites were made, as well as those on 'Opensearch (Optional)'.
On the docker-compose all config files are fine.

Also I made a mistake in the first comment, version is 2.11.1 for both Opensearch and OSD.

**Comment by lguillaud** [comment]
Do you have the same issue when using this plugin https://github.com/fbaligand/kibana-enhanced-table ?
It could be worth trying another plugin to test your saving stuff.

**Comment by LuisFFadista** [comment]
After some more in-depth testing, it was discovered that the problem was a firewall blocking requests that contained executable code. Closing the issue.
