### ISSUE TITLE
2.15.0 update?

### ISSUE THREAD

**Issue by palla89** [lguillaud/osd_transform_vis#12]
Hi! I'm trying to install your plugin on the 2.15.0 version of OpenSearch Dashboards but of course it's saying it's not made for that version, If I just change the version should it compile?

**Comment by lguillaud** [comment]
Hi,
The version number must be changed in both opensearch_dashboards.json and package.json.
I am going to create the release for that.

**Comment by palla89** [comment]
Thank you very very much for your kind and super quick answer! 
I was trying to create a new plugin for OpenSearch Dashboards to create a new visualizer, but understand the structure of how it should be done, it's not as easy as I hoped!

**Comment by lguillaud** [comment]
You're welcome.
Indeed the structure is not easy to understand. I did not write the plugin initially just forked and ported it to OSD.
The release is now available.
