### ISSUE TITLE
2.16.0 Update?

### ISSUE THREAD

**Issue by palla89** [lguillaud/osd_transform_vis#13]
Hi again! 😄 I'd need the 2.16.0 version for the new OpenSearch Dashboards release, can you add the new release when and if you have time? Thank you very much!!

**Comment by palla89** [comment]
Hi @lguillaud sorry to bother you: do you have any update for this? I've got some problems recompiling it by myself 😞

**Comment by lguillaud** [comment]
Hi @palla89 ,
Sorry for the delay.
Also had an issue with the compilation but got it solved but re-installing everything from scratch.
Currently building the version. Should be ready in a few minutes.

**Comment by lguillaud** [comment]
2.16.0 released

**Comment by palla89** [comment]
you're amazing!! don't be sorry for the delay, I'm grateful you did it for me avoiding me a lot of time to understand how to compile everything 😃 
Have a nice day mate!

**Comment by palla89** [comment]
hi @lguillaud , it's me again: I don't want to spam you with another issue, but can you upload the latest 2.17.1 version? thank you!!!

**Comment by lguillaud** [comment]
hi @palla89 ,
Done https://github.com/lguillaud/osd_transform_vis/releases/tag/2.17.1
Enjoy !

**Comment by palla89** [comment]
You are a dragon!!! 💯
