### ISSUE TITLE
Issue: Plugin transformVis [2.0.1] is incompatible with OpenSearch Dashboards [2.1.0]

### ISSUE THREAD

**Issue by mdcox** [lguillaud/osd_transform_vis#3]
- When trying to run install on this locally, I run into a compatibility issue. I know OpenSearch DB 2.1.0 is newer, is there any planned compatibility with it?

Also tried with OS 2.0.0 and got the same error:
- Plugin installation was unsuccessful due to error "Plugin transformVis [2.0.1] is incompatible with OpenSearch Dashboards [2.0.0]"

**Comment by lguillaud** [comment]
Hello,
Currently updating the config files.
Will be available very shortly :-)

**Comment by lguillaud** [comment]
done: https://github.com/lguillaud/osd_transform_vis/releases/tag/2.1.0
