### ISSUE TITLE
Apache EChart

### ISSUE THREAD

**Issue by kris4ever** [lguillaud/osd_transform_vis#4]
Hi, 
Thanks for porting this to OpenSearch!
Do you think it would be possible to run Apache ECharts JS scripts ?
Do you have an example code somewhere ?
Thanks!

**Comment by lguillaud** [comment]
Hello,
Sorry for the very late delay in response.
The plugin allows to use any JS library so I would say it is possible to use Apache Echart JS.
Will try on my side and come back to you.

**Comment by lguillaud** [comment]
I can confirm it works.
Please find enclosed the exported saved object for the example https://echarts.apache.org/handbook/en/get-started/#.

Hope it helps.
[export.zip](https://github.com/lguillaud/osd_transform_vis/files/10342640/export.zip)

**Comment by kris4ever** [comment]
Hello,
Thanks for your answer, I'll have a look at it ;-)

**Comment by lguillaud** [comment]
Added info in Readme + example in sample_vizs directory (https://github.com/lguillaud/osd_transform_vis/blob/2.x/sample_vizs/sample_sankey_with_apache_echart.ndjson)
