### ISSUE TITLE
Request :  Default Dashboards  

### ISSUE THREAD

**Issue by vvvprabhakar** [lguillaud/osd_transform_vis#5]
Hello 
I want to build default dashboards for particular index-pattern
where admin only should be able to edit it ? 

Can i make something like that using this ?

Can you suggest me an alternative? 

*Role control i can do * But looking for best approach to do the default dashboards

**Comment by lguillaud** [comment]
Hello,
I think the best to achieve what you are trying to do is to use role control: admin user with edit role and a user having read-only permissions for both OSD and indices.
The transform plugin does have any security options.
