### ISSUE TITLE
Add support for OpenSearch Dashboard Version 2.6.0

### ISSUE THREAD

**Issue by meet-node** [lguillaud/osd_transform_vis#6]
Hello,

Can you add the new release for OpenSearch Dashboard v2.6.0 as I'm getting this error: Plugin installation was unsuccessful due to error "Plugin transformVis [2.5.0] is incompatible with OpenSearch Dashboards [2.6.0]"?

Thanks

**Comment by lguillaud** [comment]
Hello @meet-hcl ,

The new version has been released.

Lionel
